### PR TITLE
Update ConsoleExtension.php

### PR DESCRIPTION
**Pull request by janzarubadek**
Lazy loading using the service tag does not work.

### CODE REVIEW

**Comment by f3l1x** [comment]
Hey ✋ @janzarubadek. Is the tag really needed? Describe me please your use-case.

**Comment by janzarubadek** [comment]
> Hey ✋ @janzarubadek. Is the tag really needed? Describe me please your use-case.

Hi, I replaced kdyby/console with this contributte/console. Without this feature, there is no point for us to use this package and it will be removed from our products. Cases of use can be seen in the old kdyby products. Thanks.

**Comment by f3l1x** [comment]
I don't get it. Why do you need use tag for lazy-loading? All commands are lazy-loaded by default by it's type. What's the case you need tag?

**Comment by janzarubadek** [comment]
> I don't get it. Why do you need use tag for lazy-loading? All commands are lazy-loaded by default by it's type. What's the case you need tag?
Kdyby DI extensions insert commands dynamically: 
$builder->addDefinition(....)->addTag(....
Sorry. I don't have the space for a complete rebuild. Many important people here consider nette a dying project etc...

Besides, it is written in your documentation that it is supported.

**Comment by f3l1x** [comment]
I will add this tag support back, just for you.

PS: Do you have Slack or something? I would like to hear about your project more and also discuss it how do use it with Kdyby, because Kdyby does not support nette v4 or does?

**Pull request merged**
